using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using HarmonyLib;
using UnityEngine;

namespace TLDRevamp.Fixes
{
    /// objGenScript.categoryClass.UpdGen generates one whole chunk of scattered objects (rocks, cacti, grass…) in one
    /// frame. Driving bench (seed 20260924, east route, 90 km/h): UpdGen max 18 ms, 25 frames >5 ms per pass.
    ///
    /// Why (from the code + in-game counts): per grid cell the game constructs TWO System.Randoms (2.37 µs each incl. a
    /// draw, measured in-game): chunkRnd, seeded only by the cell's biome chunk (10,000–40,000 cells share one), and
    /// objRnd, whose first number is the chance test that rejects ~96% of cells. SmallRocks: 2,809 cells/chunk →
    /// ~13 ms of Random construction alone.
    ///
    /// Exact speed-up: chunkRnd's result (selected chance + lerp) computed once per biome chunk; the chance test uses
    /// FastRandom.FirstDouble (allocation-free copy of System.Random seeding, checked against the real one in-game);
    /// only surviving cells construct the real objRnd (and draw the first number again, so its stream is unchanged).
    /// Everything else is the game's loop body in the game's order. Verify compares each chunk with
    /// ParallelObjGen.GenerateChunk (verified exact against the game: 999 chunks, 0 mismatches).
    /// Optional time slicing (BudgetMs > 0): a chunk is built over several frames and inserted when complete.
    ///
    /// Runtime switches (bridge `set`): TLDRevamp.Fixes.ObjGenFast.Enabled / .Verify / .BudgetMs (0 = same frame)
    [HarmonyPatch(typeof(objGenScript.categoryClass), nameof(objGenScript.categoryClass.UpdGen))]
    public static class ObjGenFast
    {
        /// On by default since v0.20.0: exact (randcheck 2M seeds, chunk verify 200 chunks: 0 mismatches), driving A/B p99 −11%, max −22%.
        public static bool Enabled = true;
        public static bool Verify = false;
        public static float BudgetMs = 0f;
        public static long MemoHits, MemoMisses, FastRejects, RealRandoms;
        public static bool UseFast = true;   // false: the same path with the game's Randoms (verify isolation)
        public static string MismatchCats = "";

        private sealed class Memo { public int SeedBase; public readonly Dictionary<Vector3d, float> Lerp = new Dictionary<Vector3d, float>(); }
        private static readonly ConditionalWeakTable<objGenScript.categoryClass, Memo> Memos = new ConditionalWeakTable<objGenScript.categoryClass, Memo>();

        public static long Chunks, Slices, Cells, Objects, Discarded, VerifyChecks, VerifyMismatches, Fallbacks;
        public static double MaxCallMs;
        public static string LastMismatch = "", LastError = "";

        private sealed class Job
        {
            public Vector3d Key;
            public objGenScript.chunkClass Chunk;
            public int Next;
            public readonly List<ParallelObjGen.Cell> Kept = new List<ParallelObjGen.Cell>();
        }
        private sealed class Holder { public Job J; }
        private static readonly ConditionalWeakTable<objGenScript.categoryClass, Holder> Jobs = new ConditionalWeakTable<objGenScript.categoryClass, Holder>();

        [HarmonyPrefix]
        private static bool Prefix(objGenScript.categoryClass __instance, bool _moreFrame)
        {
            if (!Enabled || ParallelObjGen.Enabled) return true;
            var cat = __instance;
            var script = cat.script;
            if (script == null || script.terrain == null || script.terrain.mapSetting == null || script.terrain.mapSetting.imageMapLoad != null)
                return true;
            long t0 = System.Diagnostics.Stopwatch.GetTimestamp();
            try
            {
                if (BudgetMs <= 0f || !_moreFrame) return SameFrame(cat, _moreFrame, t0);
                cat.UpdChunksNeeded();
                if (SceneryTileSync.RegenPending(cat, true))
                {
                    ParallelObjGen.RemoveUnneeded(cat);
                    return false;
                }
                var h = Jobs.GetValue(cat, _ => new Holder());
                // The chunk in progress must still be needed, still the same object, and not generated by someone else
                if (h.J != null && (!cat.chunksNeeded.Contains(h.J.Key) || !cat.generatedChunks.TryGetValue(h.J.Key, out var cur) ||
                                    cur != h.J.Chunk || cur.generated))
                {
                    h.J = null;
                    Discarded++;
                }
                if (h.J == null)
                {
                    for (int i = 0; i < cat.chunksNeeded.Count; i++)
                    {
                        var key = cat.chunksNeeded[i];
                        if (!cat.generatedChunks.ContainsKey(key)) cat.generatedChunks.Add(key, new objGenScript.chunkClass());
                        var chunk = cat.generatedChunks[key];
                        if (chunk.generated) continue;
                        h.J = new Job { Key = key, Chunk = chunk };
                        break;
                    }
                }
                if (h.J != null)
                {
                    var job = h.J;
                    int n = cat.resolution * cat.resolution;
                    while (job.Next < n)
                    {
                        var c = GenCell(cat, job.Key, job.Next);
                        job.Next++;
                        Cells++;
                        if (c != null)
                        {
                            c.Obj = ParallelObjGen.Finish(cat, c);
                            if (c.Obj != null) job.Kept.Add(c);
                        }
                        if (Ms(t0) > BudgetMs) break;
                    }
                    Slices++;
                    if (job.Next >= n)
                    {
                        if (Verify) VerifyChunk(cat, job);
                        foreach (var c in job.Kept) job.Chunk.objs.Add(c.GPosID, c.Obj);
                        job.Chunk.generated = true;
                        Chunks++;
                        Objects += job.Kept.Count;
                        h.J = null;
                    }
                }
                ParallelObjGen.RemoveUnneeded(cat);
                double ms = Ms(t0);
                if (ms > MaxCallMs) MaxCallMs = ms;
                return false;
            }
            catch (Exception e)
            {
                // Objects are only inserted when a chunk completes, so the game can simply redo an unfinished chunk
                Fallbacks++;
                LastError = e.ToString();
                Enabled = false;
                Plugin.Log.LogError("ObjGenFast disabled after error: " + e);
                return true;
            }
        }

        /// The game's structure: generate the first ungenerated needed chunk completely (all of them when !_moreFrame).
        private static bool SameFrame(objGenScript.categoryClass cat, bool moreFrame, long t0)
        {
            cat.UpdChunksNeeded();
            if (SceneryTileSync.RegenPending(cat, moreFrame) && moreFrame)
            {
                ParallelObjGen.RemoveUnneeded(cat);
                return false;
            }
            int n = cat.resolution * cat.resolution;
            for (int i = 0; i < cat.chunksNeeded.Count; i++)
            {
                var key = cat.chunksNeeded[i];
                if (!cat.generatedChunks.ContainsKey(key)) cat.generatedChunks.Add(key, new objGenScript.chunkClass());
                var chunk = cat.generatedChunks[key];
                if (chunk.generated) continue;
                var job = new Job { Key = key, Chunk = chunk };
                for (; job.Next < n; job.Next++)
                {
                    var c = GenCell(cat, key, job.Next);
                    Cells++;
                    if (c == null) continue;
                    c.Obj = ParallelObjGen.Finish(cat, c);
                    if (c.Obj != null) job.Kept.Add(c);
                }
                if (Verify) VerifyChunk(cat, job);
                foreach (var c in job.Kept) chunk.objs.Add(c.GPosID, c.Obj);
                chunk.generated = true;
                Chunks++;
                Slices++;
                Objects += job.Kept.Count;
                if (moreFrame) break;
            }
            ParallelObjGen.RemoveUnneeded(cat);
            double ms = Ms(t0);
            if (ms > MaxCallMs) MaxCallMs = ms;
            return false;
        }

        /// Drop a chunk that is being built over several frames (its cells may have used lists that just changed).
        internal static void DiscardJob(objGenScript.categoryClass cat)
        {
            if (Jobs.TryGetValue(cat, out var h) && h.J != null) { h.J = null; Discarded++; }
        }

        /// Generate an already generated chunk again from the current roads/buildings and merge (SceneryTileSync).
        internal static void Regenerate(objGenScript.categoryClass cat, Vector3d key, objGenScript.chunkClass chunk)
        {
            int n = cat.resolution * cat.resolution;
            var fresh = new Dictionary<Vector3d, objGenScript.objClass>();
            for (int idx = 0; idx < n; idx++)
            {
                var c = GenCell(cat, key, idx);
                Cells++;
                if (c == null) continue;
                var o = ParallelObjGen.Finish(cat, c);
                if (o != null) fresh.Add(c.GPosID, o);
            }
            SceneryTileSync.Merge(cat, chunk, fresh);
        }

        private static double Ms(long t0) => (System.Diagnostics.Stopwatch.GetTimestamp() - t0) * 1000.0 / System.Diagnostics.Stopwatch.Frequency;

        /// One grid cell up to the distance/height stage, exactly as the game's loop body (biome cache, chance test,
        /// jitter, destroyed check, tile cache with RoadsNear/POIsNear). null = rejected before Finish.
        private static ParallelObjGen.Cell GenCell(objGenScript.categoryClass cat, Vector3d key, int idx)
        {
            var script = cat.script;
            int res = cat.resolution;
            int j = idx / res, k = idx % res;
            int seedBase = script.mapSetting.seed + cat.rndCategoryOffset;
            Vector3d posID = key + new Vector3d(1f, 0f, 1f) * cat.offset + new Vector3d(k, 0f, j) * cat.gridSize;
            Vector3d chunkID = mainscript.GetChunkPos(posID, cat.chunkSize);
            float chanceMultiplierBiome = 1f;
            if (cat.biomes.TryGetValue(chunkID, out int biomeInt))
                chanceMultiplierBiome *= cat.biomeMultipliers[biomeInt];
            else
            {
                int biome = terrainGenSettings.GetFirstBiomeInt(chunkID);
                cat.biomes.Add(chunkID, biome);
                chanceMultiplierBiome *= cat.biomeMultipliers[biome];
            }
            // chunkRnd depends only on the biome chunk: its lerp result is the same for every cell in it
            var memo = Memos.GetValue(cat, _ => new Memo());
            if (memo.SeedBase != seedBase) { memo.Lerp.Clear(); memo.SeedBase = seedBase; }
            float lerp;
            if (!UseFast)
            {
                var cr = new System.Random(seedBase + chunkID.GetHashCode());
                int sc = ParallelObjGen.SelectRandomProperty(cat.chance, cr);
                float cc = Mathf.Lerp(cat.chance[sc].min, cat.chance[sc].max, (float)cr.NextDouble()) * cat.chanceMultiplier * chanceMultiplierBiome;
                var or = new System.Random(seedBase + posID.GetHashCode() + Mathd.Round((posID - chunkID).sqrMagnitude).GetHashCode());
                float rr = (float)or.NextDouble();
                if (rr > cc * script.globalChanceMultiplier) return null;
                return Rest(cat, script, idx, posID, chunkID, rr, cc, or);
            }
            if (memo.Lerp.TryGetValue(chunkID, out lerp)) MemoHits++;
            else
            {
                var chunkRnd = new System.Random(seedBase + chunkID.GetHashCode());
                int selectedChance = ParallelObjGen.SelectRandomProperty(cat.chance, chunkRnd);
                lerp = Mathf.Lerp(cat.chance[selectedChance].min, cat.chance[selectedChance].max, (float)chunkRnd.NextDouble());
                memo.Lerp.Add(chunkID, lerp);
                MemoMisses++;
            }
            float currentChance = lerp * cat.chanceMultiplier * chanceMultiplierBiome;
            int objSeed = seedBase + posID.GetHashCode() + Mathd.Round((posID - chunkID).sqrMagnitude).GetHashCode();
            float r = (float)FastRandom.FirstDouble(objSeed);
            if (r > currentChance * script.globalChanceMultiplier) { FastRejects++; return null; }
            var objRnd = new System.Random(objSeed);
            objRnd.NextDouble(); // the chance-test number: keep the stream where the game has it
            RealRandoms++;
            return Rest(cat, script, idx, posID, chunkID, r, currentChance, objRnd);
        }

        private static ParallelObjGen.Cell Rest(objGenScript.categoryClass cat, objGenScript script, int idx, Vector3d posID, Vector3d chunkID, float r, float currentChance, System.Random objRnd)
        {
            float tollasx = (float)objRnd.NextDouble();
            float tollasz = (float)objRnd.NextDouble();
            Vector3d gpos = posID;
            gpos.x += Mathf.Lerp(0f - cat.tollas, cat.tollas, tollasx) * cat.gridSize;
            gpos.z += Mathf.Lerp(0f - cat.tollas, cat.tollas, tollasz) * cat.gridSize;
            var c = new ParallelObjGen.Cell { Index = idx, PosID = posID, ChunkID = chunkID, GPos = gpos, GPosID = gpos, R = r, CurrentChance = currentChance, ObjRnd = objRnd };
            if (cat.saveDestroy && cat.destroyed.ContainsKey(c.ChunkID) && cat.destroyed[c.ChunkID].Contains(c.GPosID)) return null;
            if (cat.useTerrainHeight || cat.useRemoveInsidePOI || cat.minDistFromRoad > 0f || cat.maxDistFromRoad > 0f || cat.minDistFromPOI > 0f)
            {
                SceneryTileSync.Lists(script, cat.useTile, c.GPos, out var roads, out var pois);
                c.Roads = roads;
                c.Pois = pois;
            }
            return c;
        }

        /// Compare the sliced result with a one-shot generation of the same chunk (ParallelObjGen, verified exact).
        private static void VerifyChunk(objGenScript.categoryClass cat, Job job)
        {
            VerifyChecks++;
            var reference = ParallelObjGen.GenerateChunk(cat, job.Key);
            string diff = null;
            if (reference.Count != job.Kept.Count) diff = "count " + job.Kept.Count + " vs " + reference.Count;
            for (int i = 0; diff == null && i < reference.Count; i++)
            {
                var a = job.Kept[i];
                var b = reference[i];
                // Equals, not ==/!=: the game's Vector3d.operator== is `SqrMagnitude(a-b) < 0` (never true)
                if (!a.GPosID.Equals(b.GPosID)) diff = "gposID at " + i + " ours " + a.GPosID + " cell " + a.Index + " ref " + b.GPosID + " cell " + b.Index;
                else if (a.Obj.prefabIndex != b.Obj.prefabIndex) diff = "prefab at " + i;
                else if (a.Obj.seed != b.Obj.seed) diff = "seed at " + i;
                else if (!a.Obj.rot.Equals(b.Obj.rot)) diff = "rot at " + i;
                else if (a.Obj.scale != b.Obj.scale) diff = "scale at " + i;
                else if (!a.Obj.gpos.Equals(b.Obj.gpos)) diff = "gpos at " + i;
                else if (a.Index != b.Index) diff = "cell at " + i;
            }
            if (diff != null)
            {
                VerifyMismatches++;
                LastMismatch = cat.name + " " + job.Key + ": " + diff;
                if (!MismatchCats.Contains(cat.name)) MismatchCats += cat.name + " ";
            }
        }

        public static string Stats =>
            "{\"enabled\":" + (Enabled ? "true" : "false") + ",\"verify\":" + (Verify ? "true" : "false") + ",\"budgetMs\":" + BudgetMs +
            ",\"chunks\":" + Chunks + ",\"slices\":" + Slices + ",\"cells\":" + Cells + ",\"objects\":" + Objects +
            ",\"discarded\":" + Discarded + ",\"maxCallMs\":" + MaxCallMs.ToString("F2") +
            ",\"verifyChecks\":" + VerifyChecks + ",\"verifyMismatches\":" + VerifyMismatches + ",\"fallbacks\":" + Fallbacks +
            ",\"memoHits\":" + MemoHits + ",\"memoMisses\":" + MemoMisses + ",\"fastRejects\":" + FastRejects + ",\"realRandoms\":" + RealRandoms +
            ",\"useFast\":" + (UseFast ? "true" : "false") + ",\"mismatchCats\":" + Json.Str(MismatchCats) +
            ",\"lastMismatch\":" + Json.Str(LastMismatch) + ",\"lastError\":" + Json.Str(LastError) + "}";
    }
}
